### ISSUE TITLE
Need to verify if websocket data is revceived

### ISSUE THREAD

**Issue by forkineye** [forkineye/ESPixelStick#65]
Sometimes, configuration data fails to show up in the web UI.  Root cause is unknown, however configuration receipt verification / re-querying should be done to prevent this from happening.
Example: https://diychristmas.org/vb1/showthread.php?7969-ESPixelStick-WiFi-Renard-amp-Pixel-Control-from-XLights&p=88776&viewfull=1#post88776

**Comment by cinoan** [comment]
Traced it to ESPAsyncWebServer before but didn't get a fix and haven't had chance to look recently - https://github.com/me-no-dev/ESPAsyncWebServer/issues/138

Sending one message, e.g
`ws.send('E1#G1#G2');`
and handling that rather than the current
`ws.send('E1'); // Get html elements
ws.send('G1'); // Get Config
ws.send('G2'); // Get Net Status`
would probably avoid the issue.

**Comment by forkineye** [comment]
@cinoan Appreciate the help, thanks!  I'll look into it.

**Comment by forkineye** [comment]
@cinoan I'm having issues re-creating this locally.  It looks as if it may have fixed here - https://github.com/me-no-dev/ESPAsyncWebServer/pull/144.  They have since fixed the IE issue as well so my fork of ESPAsyncWebServer should no longer be required.  Any chance you can see if the latest ESPAsyncWebServer upstream still has the issue?

**Comment by cinoan** [comment]
@forkineye Sorry I hadn't got back to this before. Just tried updating the ESPAsync libraries and still getting the same issue with messages being missed. Short on time at the moment but will try to find some to look at it.
