### ISSUE TITLE
espixelstick stops functioning after about 5min

### ISSUE THREAD

**Issue by stijn-dhondt** [forkineye/ESPixelStick#657]
--------- Instructions --------
Please provide answers directly below each section.
--------- Instructions ---------

**ESPixelStick Firmware Version**
4.0-ci5943922254

**Hardware Version**
quinled quad ETH
but have same issues with Uno and Octa

**Binary release or compiled yourself?**
release

**Operating System (and version)**
Windows

**Web Browser (and version)**
Version 114.0.5735.199 (Official build) (64-bits)

**Access Point**
Ubiquity unifi UAP-AC-Pro

**Describe the bug**
ESP 32 boots comes as available controller in FPP player but after about 5min controller goes offline and does not respond to anything anymore. Until i power cycly the device it stay's offline. 
As from that point the same issue just repaets.

even if i send ping to the device so it stays awake it just stops functioning. 
Also no response on the console just no more comms..

**Comment by stijn-dhondt** [comment]
Xlights 2023.13 on mac 
FPP 7.1 git 5f5cfcc
I already tested the firmware on following Quin boards:
- Dig Uno wifi only
- Dig Quad eth and wifi
- Dig Octa eth and wifi

all dropping all of the communication within less than 5min...
Don't think Xlights and FPP are the issue here it's really the ESP that completely stops responding..
Even the console does not output anything...

**Comment by rledonne** [comment]
I believe I am having a similar issue that may be the same thing.  I added comments as a discussion.
https://github.com/forkineye/ESPixelStick/discussions/659

It will stay connected until you open Tools | Test in xLights and start to send it data.  Then it goes offline and doesn't reconnect until power cycled.

**Comment by rledonne** [comment]
Adding an update.  
I noticed that the network connection will drop randomly and not reconnect after a few minutes, regardless of whether I send data or not.  Sending data to it just makes it happen faster.

If I add a fseq to the sd card and play it from the firmware, it will continue playing and looping after the network connection drops.

I am available to troubleshoot, I just don't know how to get any useful information since it a wifi device, and no logging, or maybe I am missing it.

**Comment by stijn-dhondt** [comment]
> Adding an update. I noticed that the network connection will drop randomly and not reconnect after a few minutes, regardless of whether I send data or not. Sending data to it just makes it happen faster.
> 
> If I add a fseq to the sd card and play it from the firmware, it will continue playing and looping after the network connection drops.
> 
> I am available to troubleshoot, I just don't know how to get any useful information since it a wifi device, and no logging, or maybe I am missing it.

Turned off DDP and did not solve the issue on all 3 controllers and no change so DDP is not the source of the issue here.
Seem that we really are looking at a similar issue with your update now. Great to not be alone here ;-)

**Comment by stijn-dhondt** [comment]
@patdelaney are you able to reproduce the issue?

**Comment by stijn-dhondt** [comment]
found version 4.0-ci3677767017 on an older system and this one seems to work normal... but that's one of 12 dec 2022.

**Comment by MartinMueller2003** [comment]
Please try this version: https://github.com/MartinMueller2003/ESPixelStick/blob/main/dist.zip

Please leave  the ESP connected to the flashtool. Do whatever it is you normally do to cause it to disconnect. Save the logs and attach them to this issue.

**Comment by stijn-dhondt** [comment]
[Log.txt](https://github.com/forkineye/ESPixelStick/files/12651508/Log.txt)

@MartinMueller2003, Logs attached... I started the esp arround 18:56:30 and it went offline from wifi today at 19:03:50 but no logs appeared at that time...

**Comment by MartinMueller2003** [comment]
Interesting that the wired interface came up but never got an IP address. That may be causing an internal routing conflict.  Can you post your network config screen?

**Comment by stijn-dhondt** [comment]
<img width="749" alt="Screenshot 2023-09-18 at 20 18 07" src="https://github.com/forkineye/ESPixelStick/assets/50807033/dbd89e3f-745f-48f1-84e7-a491ee8bfe0f">

This is the last config i tested, before i had DHCP turned on with the same issue, and i also tested with the same ip on the ethernet interface which should be an issue anyway but in all 3 cases there was nothing connected to the ethernet interface...

**Comment by MartinMueller2003** [comment]
I never tested With nothing plugged into the Ethernet port and the IP set to static.

**Comment by rledonne** [comment]
I will add mine as well....
[AEplus Log.txt](https://github.com/forkineye/ESPixelStick/files/12652547/AEplus.Log.txt)

This was after a fresh flash using the above zip.
It flashed fine, connected to wifi, and watching it in the router, was connected for about 30 seconds before it dropped.  During that 30 seconds, I clicked the output to lights in xlights, and started a sequence.

**Comment by stijn-dhondt** [comment]
@MartinMueller2003 just had 1 time the exact same issue in the logging as @rledonne! other times the console just stays silent...

**Comment by rledonne** [comment]
This one was flashed and nothing was done after it was flashed yesterday afternoon.  It just sat connected to the computer.  It looks like it dropped overnight and never tried to reconnect.

[AEplus Log2.txt](https://github.com/forkineye/ESPixelStick/files/12672675/AEplus.Log2.txt)

**Comment by MartinMueller2003** [comment]
Now that is MUCH more interesting. These three lines are odd:
This line indicates the web page asked for the files needed to display and started working
16:19:31: [ 32710][E][vfs_api.cpp:104] open(): /littlefs/www/esps.css does not exist, no permits for creation

This line indicates there was a problem working with the AP. This one is VERY odd because the ESP should have stopped transferring data right away.
16:19:50: [WiFiDrv] WiFi Lost the connection to the AP

And this is when the ESP finally gave up interacting with the AP.
03:03:17: [WiFiDrv] WiFi Entering State: Connection Failed

Now to try and replicate what is going on. FYI: I ran mine overnight last night with no issues.

**Comment by rledonne** [comment]
Sorry, I just remembered this.
I think the line 16:19:31: [ 32710][E][vfs_api.cpp:104] open(): /littlefs/www/esps.css does not exist, no permits for creation happened when I did go to the Network Settings page to make sure it was connected and since you had asked for a screenshot earlier, but there was nothing really there, just the DHCP box and AP Reboot checked.

It did sit  with "16:19:50:                                     "  in the serial output while waiting.  My guess is when it dropped around 3am, it finished that line with  [WiFiDrv] WiFi Lost the connection to the AP

**Comment by rledonne** [comment]
Please let me know if there is any other way that I can help.

**Comment by stijn-dhondt** [comment]
just a quick update!
I started using the latest version and had similar issues.
I removed the FPP 7.1 from the network for now just to eliminate possible sources and all 3 controllers (Dig Uno, Quad and octa remaining online for now. so it sees that at first site FPP is causing the issue. 

Will downgrade FPP to a stable version later today. @rledonne which fpp version are you running?

**Comment by MartinMueller2003** [comment]
Excellent. That is something I can work with.

**Comment by stijn-dhondt** [comment]
> Excellent. That is something I can work with.

@MartinMueller2003 6.3.2 seems to be stable  except for when the controllers are connected trough ethernet they show up in FPP with ip 0.0.0.0

<img width="1544" alt="Screenshot 2023-09-24 at 18 03 58" src="https://github.com/forkineye/ESPixelStick/assets/50807033/b0dc2fae-d212-45d2-a98f-2e485f2101b3">

**Comment by MartinMueller2003** [comment]
Added FPP 7.1 to my network (I stopped at 5.3 because I don't agree with the new hat license) and I see the heap dropping regularly. After about 5 minutes the heap drops to a level where no network traffic gets through the system. Only happens when FPP 7 is sending updates. Time to start debugging :)

**Comment by MartinMueller2003** [comment]
Please try the dist.zip found here: https://drive.google.com/drive/folders/1bGrkXSMoGjWtX5iWspPFRogM2G6c1VXu?usp=sharing

**Comment by stijn-dhondt** [comment]
@MartinMueller2003 just tested a dig quad trough wifi and ethernet and working fine now!

Do you want me to test a dig uno and Octa also?

**Comment by MartinMueller2003** [comment]
That would be good but the code is common so if it works on one it should work on the others.
Martin
    On Tuesday, September 26, 2023 at 03:00:12 AM EDT, stijn-dhondt ***@***.***> wrote:  
 
 


@MartinMueller2003 just tested a dig quad trough wifi and ethernet and working fine now!

Do you want me to test a dig uno and Octa also?

**Comment by MartinMueller2003** [comment]
I fixed a memory leak in the file close process. It was possible to miss closing a file.

**Comment by stijn-dhondt** [comment]
Still have some strange issues but give me some time to come back trying to pinpoint it first...

**Comment by stijn-dhondt** [comment]
@MartinMueller2003 Looking good for now! Controller has been online the whole night. Can you let us know when the update will be available in CI build?

**Comment by MartinMueller2003** [comment]
Fixed in: [Fixed memory leak](https://github.com/forkineye/ESPixelStick/pull/668#top)
#668
